/*
Project Title: Movies Database Analysis
Database Name: movies
Author: Rushikesh Wakle
Date: January 2, 2026
Description: This script contains basic, intermediate, Advance analysis queries 
             for the movie, actor, and director dataset.
*/


create database movies;
use movies;

-- I Imported CSV Files for all the tables in this database.
-- Questions
-- 1. Retrieve all information for movies released in the year 2010.
SELECT * FROM movies_en 
WHERE ReleaseYear = 2010;


-- 2. List the unique nationalities of all directors in the database.
SELECT DISTINCT Nationality 
FROM directors_en;


-- 3. Count how many users are registered from the 'USA'.
SELECT COUNT(*) 
FROM users_en 
WHERE Country = 'USA';


-- 4. Find the titles and durations of movies that are longer than 150 minutes.
SELECT Title, DurationMinutes 
FROM movies_en
WHERE DurationMinutes > 150;


-- 5. List the names (FirstName, LastName) of all female actors.
SELECT FirstName, LastName 
FROM actors_en
WHERE Gender = 'Female';


-- 6. Show the top 10 movies with the highest budget, ordered from highest to lowest.
SELECT Title, Budget 
FROM movies_en
ORDER BY Budget DESC 
LIMIT 10;


-- 7. Get the total number of awards won by all actors combined.
SELECT SUM(AwardsCount) AS TotalActorAwards 
FROM actors_en;


-- 8. Find all movies where the language is 'French'.
SELECT Title 
FROM movies_en
WHERE Language = 'French';


-- 9. List the names of users who registered after January 1st, 2024.
SELECT UserName, RegistrationDate 
FROM users_en
WHERE RegistrationDate > '2024-01-01';


-- 10. Select the description of the genre named 'Sci-Fi' or 'Science Fiction'.
SELECT Description 
FROM genres_en 
WHERE GenreName = 'Science Fiction';


-- 11. List every movie title along with its corresponding genre name.
SELECT m.Title, g.GenreName 
FROM movies_en m
JOIN genres_en g ON m.GenreID = g.GenreID;


-- 12. Find the average rating value for each movie (Show Movie ID and Average Rating).
SELECT MovieID, AVG(RatingValue) AS AverageRating
FROM ratings_en
GROUP BY MovieID;


-- 13. List the names of actors and the number of movies they have acted in, but only for those who have been in more than 2 movies.
SELECT a.FirstName, a.LastName, COUNT(ma.MovieID) AS MovieCount
FROM actors_en a
JOIN movie_actors_en ma ON a.ActorID = ma.ActorID
GROUP BY a.ActorID, a.FirstName, a.LastName
HAVING MovieCount > 2;


-- 14. Find the names of directors who have directed movies in the 'Action' genre.
SELECT DISTINCT d.FirstName, d.LastName
FROM directors_en d
JOIN movies_en m ON d.DirectorID = m.DirectorID
JOIN genres_en g ON m.GenreID = g.GenreID
WHERE g.GenreName = 'Action';


-- 15. Calculate the total Box Office revenue generated by each country's movies.
SELECT Country, SUM(BoxOffice) AS TotalRevenue
FROM movies_en
GROUP BY Country
ORDER BY TotalRevenue DESC;


-- 16. Identify movies that have a budget higher than the average budget of all movies in the database.
SELECT Title, Budget
FROM movies_en
WHERE Budget > (SELECT AVG(Budget) FROM movies_en);


-- 17. List the names of all actors who played a 'Main Character' role in the movie titled 'Inception' (or any specific title).
SELECT a.FirstName, a.LastName
FROM actors_en a
JOIN movie_actors_en ma ON a.ActorID = ma.ActorID
JOIN movies_en m ON ma.MovieID = m.MovieID
WHERE m.Title = 'Inception' AND ma.IsMainCharacter = 1;


-- 18. Show the top 5 countries that have the highest number of registered users.
SELECT Country, COUNT(UserID) AS UserCount
FROM users_en
GROUP BY Country
ORDER BY UserCount DESC
LIMIT 5;


-- 19. Find movies that have not received any ratings yet (using a LEFT JOIN).
SELECT m.Title
FROM movies_en m
LEFT JOIN ratings_en r ON m.MovieID = r.MovieID
WHERE r.RatingID IS NULL;


-- 20. Calculate the profit (BoxOffice - Budget) for each movie and list the top 5 most profitable movies.
SELECT Title, (BoxOffice - Budget) AS Profit
FROM movies_en
ORDER BY Profit DESC
LIMIT 5;



